[project]
name = "ragbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.8.1",
    "pypdf>=6.3.0",
    "qdrant-client>=1.16.0",
    "tiktoken>=0.12.0",
]
